### ISSUE TITLE
Error on latest release

### ISSUE THREAD

**Issue by Bufferless** [Folia-Inquisitors/WorldGuard-Folia#3]
### WorldEdit Version

FastAsyncWorldEdit-0

### WorldGuard Version

worldguard-bukkit-7.1.0-SNAPSHOT-dist

### Platform Version

Folia-36e5e83

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When putting the latest release that is provided on the Github, there are errors that will produce 

### Expected Behavior

To not see theses errors.

### Reproduction Steps

1. Use 1.20.6 Folia
2. Install FAWE Folia and the latest release of this.
3. Put it on server and join.

### Anything Else?

[01:43:56] [Region Scheduler Thread #1/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuard v7.1.0-SNAPSHOT+c41f279
java.lang.NoSuchMethodError: 'int com.sk89q.worldedit.math.BlockVector2.x()'
	at Worldguard-7.1.0-SNAPSHOT.jar/com.sk89q.worldguard.protection.managers.index.ChunkHashTable.forget(ChunkHashTable.java:182) ~[Worldguard-7.1.0-SNAPSHOT.jar:?]
	at Worldguard-7.1.0-SNAPSHOT.jar/com.sk89q.worldguard.protection.managers.RegionManager.unloadChunk(RegionManager.java:175) ~[Worldguard-7.1.0-SNAPSHOT.jar:?]
	at Worldguard-7.1.0-SNAPSHOT.jar/com.sk89q.worldguard.bukkit.BukkitRegionContainer$1.onChunkUnload(BukkitRegionContainer.java:93) ~[Worldguard-7.1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-36e5e83]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.unloadCallback(LevelChunk.java:827) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkUnload(LevelChunk.java:754) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1373) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1538) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1516) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1468) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:897) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:62) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:429) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:953) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1880) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:469) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1708) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Yomamaeatstoes** [comment]
> ### WorldEdit Version
> FastAsyncWorldEdit-0
> 
> ### WorldGuard Version
> worldguard-bukkit-7.1.0-SNAPSHOT-dist
> 
> ### Platform Version
> Folia-36e5e83
> 
> ### Confirmations
> * [x]  I am using the most recent Minecraft release.
> * [x]  I am using a version of WorldEdit compatible with my Minecraft version.
> * [x]  I am using a version of WorldGuard compatible with my Minecraft version.
> * [x]  I am using the latest or recommended version of my platform software.
> * [x]  I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
> * [x]  I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)
> 
> ### Bug Description
> When putting the latest release that is provided on the Github, there are errors that will produce
> 
> ### Expected Behavior
> To not see theses errors.
> 
> ### Reproduction Steps
> 1. Use 1.20.6 Folia
> 2. Install FAWE Folia and the latest release of this.
> 3. Put it on server and join.
> 
> ### Optional WorldGuard-Report
> _No response_
> 
> ### Anything Else?
> [01:43:56] [Region Scheduler Thread #1/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuard v7.1.0-SNAPSHOT+c41f279 java.lang.NoSuchMethodError: 'int com.sk89q.worldedit.math.BlockVector2.x()' at Worldguard-7.1.0-SNAPSHOT.jar/com.sk89q.worldguard.protection.managers.index.ChunkHashTable.forget(ChunkHashTable.java:182) ~[Worldguard-7.1.0-SNAPSHOT.jar:?] at Worldguard-7.1.0-SNAPSHOT.jar/com.sk89q.worldguard.protection.managers.RegionManager.unloadChunk(RegionManager.java:175) ~[Worldguard-7.1.0-SNAPSHOT.jar:?] at Worldguard-7.1.0-SNAPSHOT.jar/com.sk89q.worldguard.bukkit.BukkitRegionContainer$1.onChunkUnload(BukkitRegionContainer.java:93) ~[Worldguard-7.1.0-SNAPSHOT.jar:?] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-36e5e83] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?] at net.minecraft.world.level.chunk.LevelChunk.unloadCallback(LevelChunk.java:827) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.world.level.chunk.LevelChunk.onChunkUnload(LevelChunk.java:754) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1373) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1538) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1516) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1468) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:897) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:62) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:429) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:953) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1880) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:469) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1708) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

I haven't encourtered this issue. Try the latest version.
